version: '3.7'

services:

  web:
    build: ./
    command : python manage.py runserver 0.0.0.0:8000
    ports:
      - target: 8000
        published: 80
        protocol: tcp
        mode: host
    links:
      - db:db
    depends_on:
      - db
    env_file:
      - ./.env.dev
  db:
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_DB=mindkeepr_db

