# Generated by Django 3.0.5 on 2020-05-02 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('Mindkeepr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowevent',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='buyevent',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='consumeevent',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='maintenanceevent',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='returnevent',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='sellevent',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='useevent',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='event',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_inventaire.event_set+', to='contenttypes.ContentType'),
        ),
    ]
