# Generated by Django 3.0.5 on 2020-05-03 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0002_auto_20200502_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='element_attached',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='Mindkeepr.Element'),
        ),
    ]
