# Generated by Django 3.0.5 on 2020-05-12 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mindkeepr', '0004_auto_20200507_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='buyevent',
            name='supplier',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='supplier'),
        ),
        migrations.AlterField(
            model_name='element',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Mindkeepr.Category'),
        ),
    ]
