# Generated by Django 3.0.5 on 2020-08-02 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mindkeepr', '0006_auto_20200518_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Mindkeepr.Event')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('FREE', 'Free')], max_length=200, verbose_name='Status')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('Mindkeepr.event',),
        ),
        migrations.CreateModel(
            name='UnUseEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Mindkeepr.Event')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('Mindkeepr.event',),
        ),
        migrations.RemoveConstraint(
            model_name='stockrepartition',
            name='Unique set of location, status and element',
        ),
        migrations.RemoveField(
            model_name='borrowevent',
            name='name',
        ),
        migrations.RemoveField(
            model_name='returnevent',
            name='name',
        ),
        migrations.AddField(
            model_name='maintenanceevent',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenanceevent',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Execution date'),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockrepartition',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'Reserved'), ('FREE', 'Free')], max_length=200, verbose_name='Status'),
        ),
        migrations.AddConstraint(
            model_name='stockrepartition',
            constraint=models.UniqueConstraint(fields=('element', 'location', 'status', 'project'), name='Unique set of location, status and element'),
        ),
        migrations.AddField(
            model_name='unuseevent',
            name='element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unuse_history', to='Mindkeepr.Element'),
        ),
        migrations.AddField(
            model_name='unuseevent',
            name='location_destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_for_unuse_event', to='Mindkeepr.Location'),
        ),
        migrations.AddField(
            model_name='unuseevent',
            name='location_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_for_unuse_event', to='Mindkeepr.Location'),
        ),
        migrations.AddField(
            model_name='moveevent',
            name='element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='move_history', to='Mindkeepr.Element'),
        ),
        migrations.AddField(
            model_name='moveevent',
            name='location_destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_for_move_event', to='Mindkeepr.Location'),
        ),
        migrations.AddField(
            model_name='moveevent',
            name='location_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_for_move_event', to='Mindkeepr.Location'),
        ),
    ]
