# Generated by Django 3.0.5 on 2020-08-02 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0009_auto_20200802_0912'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attribute',
            name='Unique set of element and value',
        ),
        migrations.AddField(
            model_name='element',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='element',
            name='default_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mindkeepr.Location'),
        ),
        migrations.AddConstraint(
            model_name='attribute',
            constraint=models.UniqueConstraint(fields=('element_attached', 'name'), name='Unique set of element and name'),
        ),
    ]
