# Generated by Django 3.0.5 on 2020-08-07 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0019_auto_20200807_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='status_comment',
        ),
        migrations.AlterField(
            model_name='machine',
            name='status',
            field=models.CharField(choices=[('TRA', 'To be disposed'), ('INV', 'To be tested'), ('REP', 'To be repared'), ('REF', 'To be refilled'), ('MEH', 'Partially working'), ('OK', 'Working')], default='OK', max_length=3),
        ),
        migrations.CreateModel(
            name='IncidentEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Mindkeepr.Event')),
                ('new_status', models.CharField(choices=[('TRA', 'To be disposed'), ('INV', 'To be tested'), ('REP', 'To be repared'), ('REF', 'To be refilled'), ('MEH', 'Partially working'), ('OK', 'Working')], default='INV', max_length=3)),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_history', to='Mindkeepr.Machine')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('Mindkeepr.event',),
        ),
    ]
