# Generated by Django 3.0.5 on 2020-08-30 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mindkeepr', '0028_auto_20200823_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowevent',
            name='element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrow_history', to='Mindkeepr.Element'),
        ),
        migrations.AlterField(
            model_name='buyevent',
            name='element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy_history', to='Mindkeepr.Element'),
        ),
        migrations.AlterField(
            model_name='consumeevent',
            name='element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consume_history', to='Mindkeepr.Element'),
        ),
        migrations.AlterField(
            model_name='event',
            name='recording_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Recording date'),
        ),
        migrations.AlterField(
            model_name='incidentevent',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_history', to='Mindkeepr.Machine'),
        ),
        migrations.AlterField(
            model_name='maintenanceevent',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_history', to='Mindkeepr.Machine'),
        ),
        migrations.AlterField(
            model_name='moveevent',
            name='element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='move_history', to='Mindkeepr.Element'),
        ),
        migrations.AlterField(
            model_name='printelement',
            name='element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Mindkeepr.Element'),
        ),
        migrations.AlterField(
            model_name='printelement',
            name='print_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='printelements', to='Mindkeepr.PrintList'),
        ),
        migrations.AlterField(
            model_name='printlist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='returnevent',
            name='borrow_associated',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_event', to='Mindkeepr.BorrowEvent'),
        ),
        migrations.AlterField(
            model_name='sellevent',
            name='element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sell_history', to='Mindkeepr.Element'),
        ),
        migrations.AlterField(
            model_name='stockrepartition',
            name='element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_repartitions', to='Mindkeepr.Element'),
        ),
        migrations.AlterField(
            model_name='stockrepartition',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_repartitions', to='Mindkeepr.Location'),
        ),
        migrations.AlterField(
            model_name='stockrepartition',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_repartitions', to='Mindkeepr.Project'),
        ),
        migrations.AlterField(
            model_name='unuseevent',
            name='element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unuse_history', to='Mindkeepr.Element'),
        ),
        migrations.AlterField(
            model_name='useevent',
            name='element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='use_history', to='Mindkeepr.Element'),
        ),
    ]
