# Generated by Django 3.0.5 on 2020-09-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0039_auto_20200913_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='extra',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='extra'),
        ),
    ]
