# Generated by Django 3.0.5 on 2021-09-02 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0044_auto_20210815_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_genre', models.CharField(choices=[('ACT', 'Action'), ('ADV', 'Adventure'), ('ANI', 'Animation'), ('COM', 'Comedy'), ('CRI', 'Crime'), ('DRA', 'Drama'), ('FAM', 'Family'), ('FAN', 'Fantasy'), ('HIS', 'History'), ('HOR', 'Horror'), ('MUS', 'Music'), ('MYS', 'Mystery'), ('ROM', 'Romance'), ('SFI', 'Science Fiction'), ('TVM', 'TV Movie'), ('THR', 'Thriller'), ('WAR', 'War'), ('WES', 'Western'), ('UNK', 'Unknown')], default='UNK', max_length=3)),
                ('second_genre', models.CharField(choices=[('ACT', 'Action'), ('ADV', 'Adventure'), ('ANI', 'Animation'), ('COM', 'Comedy'), ('CRI', 'Crime'), ('DRA', 'Drama'), ('FAM', 'Family'), ('FAN', 'Fantasy'), ('HIS', 'History'), ('HOR', 'Horror'), ('MUS', 'Music'), ('MYS', 'Mystery'), ('ROM', 'Romance'), ('SFI', 'Science Fiction'), ('TVM', 'TV Movie'), ('THR', 'Thriller'), ('WAR', 'War'), ('WES', 'Western'), ('UNK', 'Unknown')], default='UNK', max_length=3)),
                ('summary', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='element',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='location',
            name='tags',
        ),
        migrations.CreateModel(
            name='MovieCase',
            fields=[
                ('element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Mindkeepr.Element')),
                ('custom_id', models.IntegerField(unique=True, verbose_name='Custom id')),
                ('ean', models.CharField(max_length=13)),
                ('nb_disk', models.IntegerField(verbose_name='Number of disks')),
                ('format_disk', models.CharField(choices=[('DVD', 'DVD'), ('BLU', 'Bluray'), ('UNK', 'UNKNOWN')], default='UNK', max_length=3)),
                ('subformat_disk', models.CharField(choices=[('DVD', 'DVD'), ('DVB', 'DVD + Bluray'), ('BLU', 'Bluray'), ('B3D', 'Bluray 3D'), ('B4K', 'Bluray 4K'), ('UNK', 'UNKNOWN')], default='UNK', max_length=3)),
                ('category_box', models.CharField(choices=[('DVD', 'DVD'), ('DVB', 'DVD + Bluray'), ('BLU', 'Bluray'), ('B3D', 'Bluray 3D'), ('B4K', 'Bluray 4K'), ('UNK', 'UNKNOWN')], default='UNK', max_length=3)),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='Mindkeepr.Movie')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('Mindkeepr.element',),
        ),
    ]
