# Generated by Django 3.0.5 on 2021-09-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0048_auto_20210917_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moveevent',
            name='status',
            field=models.CharField(choices=[('FREE', 'Free'), ('RESERVED', 'Reserved')], max_length=200, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='vote_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moviecase',
            name='category_box',
            field=models.CharField(choices=[('CHI', 'Children'), ('HOR', 'Horror'), ('NEW', 'New'), ('COM', 'Comedy'), ('DRA', 'Drama'), ('ACT', 'Action')], default='UNK', max_length=3),
        ),
        migrations.AlterField(
            model_name='stockrepartition',
            name='status',
            field=models.CharField(choices=[('FREE', 'Free'), ('RESERVED', 'Reserved')], max_length=200, verbose_name='Status'),
        ),
    ]
