# Generated by Django 3.0.5 on 2021-09-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0049_auto_20210917_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='backdrop_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='first_genre',
            field=models.CharField(choices=[('ACT', 'Action'), ('ADV', 'Adventure'), ('ANI', 'Animation'), ('COM', 'Comedy'), ('CRI', 'Crime'), ('DRA', 'Drama'), ('DOC', 'Documentary'), ('FAM', 'Family'), ('FAN', 'Fantasy'), ('HIS', 'History'), ('HOR', 'Horror'), ('MUS', 'Music'), ('MYS', 'Mystery'), ('ROM', 'Romance'), ('SFI', 'Science Fiction'), ('TVM', 'TV Movie'), ('THR', 'Thriller'), ('WAR', 'War'), ('WES', 'Western'), ('UNK', 'Unknown')], default='UNK', max_length=3),
        ),
        migrations.AlterField(
            model_name='movie',
            name='second_genre',
            field=models.CharField(choices=[('ACT', 'Action'), ('ADV', 'Adventure'), ('ANI', 'Animation'), ('COM', 'Comedy'), ('CRI', 'Crime'), ('DRA', 'Drama'), ('DOC', 'Documentary'), ('FAM', 'Family'), ('FAN', 'Fantasy'), ('HIS', 'History'), ('HOR', 'Horror'), ('MUS', 'Music'), ('MYS', 'Mystery'), ('ROM', 'Romance'), ('SFI', 'Science Fiction'), ('TVM', 'TV Movie'), ('THR', 'Thriller'), ('WAR', 'War'), ('WES', 'Western'), ('UNK', 'Unknown')], default='UNK', max_length=3),
        ),
    ]
