# Generated by Django 3.0.5 on 2021-09-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0052_auto_20210919_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moveevent',
            name='status',
            field=models.CharField(choices=[('FREE', 'Free'), ('RESERVED', 'Reserved')], max_length=200, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='moviecase',
            name='format_disk',
            field=models.CharField(choices=[('DVD', 'DVD'), ('BLU', 'Bluray'), ('UNK', 'UNKNOWN')], default='BLU', max_length=3),
        ),
        migrations.AlterField(
            model_name='moviecase',
            name='subformat_disk',
            field=models.CharField(choices=[('DVD', 'DVD'), ('DVB', 'DVD + Bluray'), ('BLU', 'Bluray'), ('B3D', 'Bluray 3D'), ('B4K', 'Bluray 4K'), ('UNK', 'UNKNOWN')], default='BLU', max_length=3),
        ),
        migrations.AlterField(
            model_name='stockrepartition',
            name='status',
            field=models.CharField(choices=[('FREE', 'Free'), ('RESERVED', 'Reserved')], max_length=200, verbose_name='Status'),
        ),
    ]
