# Generated by Django 3.0.5 on 2021-09-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0053_auto_20210919_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moveevent',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'Reserved'), ('FREE', 'Free')], max_length=200, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='catch_phrase',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='moviecase',
            name='ean',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='moviecase',
            name='format_disk',
            field=models.CharField(choices=[('DVD', 'DVD'), ('BLU', 'Bluray')], default='BLU', max_length=3),
        ),
        migrations.AlterField(
            model_name='moviecase',
            name='subformat_disk',
            field=models.CharField(choices=[('DVD', 'DVD'), ('BLU', 'Bluray'), ('B3D', 'Bluray 3D'), ('BB3', 'Bluray + Bluray 3D'), ('B4K', 'Bluray 4K'), ('BB4', 'Bluray + Bluray 4K')], default='BLU', max_length=3),
        ),
        migrations.AlterField(
            model_name='stockrepartition',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'Reserved'), ('FREE', 'Free')], max_length=200, verbose_name='Status'),
        ),
    ]
