# Generated by Django 3.0.5 on 2021-09-24 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0055_auto_20210924_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviegenre',
            name='remote_api_id',
        ),
    ]
