# Generated by Django 3.0.5 on 2021-10-03 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mindkeepr', '0059_auto_20211003_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialBorrowEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Mindkeepr.Event')),
                ('scheduled_borrow_date', models.DateField(verbose_name='Scheduled borrow date')),
                ('scheduled_return_date', models.DateField(verbose_name='Scheduled return date')),
                ('beneficiary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('element', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='future_borrows', to='Mindkeepr.Element')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('Mindkeepr.event',),
        ),
        migrations.DeleteModel(
            name='PotentialBorrow',
        ),
    ]
