# Generated by Django 3.0.5 on 2021-12-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0060_auto_20211003_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowevent',
            name='scheduled_borrow_date',
            field=models.DateField(null=True, verbose_name='Scheduled borrow date'),
        ),
        migrations.AlterField(
            model_name='element',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='element_images'),
        ),
        migrations.AlterField(
            model_name='moveevent',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'Reserved'), ('FREE', 'Free')], max_length=200, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='backdrop_image',
            field=models.ImageField(blank=True, null=True, upload_to='movie_images/backdrop'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='movie_images/poster'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images'),
        ),
        migrations.AlterField(
            model_name='stockrepartition',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'Reserved'), ('FREE', 'Free')], max_length=200, verbose_name='Status'),
        ),
        migrations.DeleteModel(
            name='PotentialBorrowEvent',
        ),
    ]
