# Generated by Django 3.0.5 on 2021-12-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0061_auto_20211219_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowevent',
            name='active',
            field=models.BooleanField(default='True'),
        ),
    ]
