# Generated by Django 3.0.5 on 2022-01-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0065_auto_20211231_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowevent',
            name='active',
        ),
        migrations.AlterField(
            model_name='borrowevent',
            name='state',
            field=models.CharField(choices=[('NOT_THERE', 'Non existant'), ('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('DONE', 'Completed'), ('CANCELLED', 'Cancelled')], default='NOT_THERE', max_length=11),
        ),
    ]
