# Generated by Django 3.0.5 on 2022-01-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0066_auto_20220109_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowevent',
            name='borrow_date_display',
            field=models.DateField(null=True, verbose_name='Displayable borrow date'),
        ),
        migrations.AddField(
            model_name='borrowevent',
            name='return_date_display',
            field=models.DateField(null=True, verbose_name='Displayable return date'),
        ),
        migrations.AlterField(
            model_name='moveevent',
            name='status',
            field=models.CharField(choices=[('FREE', 'Free'), ('RESERVED', 'Reserved')], max_length=200, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='stockrepartition',
            name='status',
            field=models.CharField(choices=[('FREE', 'Free'), ('RESERVED', 'Reserved')], max_length=200, verbose_name='Status'),
        ),
    ]
