# Generated by Django 3.0.5 on 2022-01-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0067_auto_20220109_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='custom_id',
            field=models.IntegerField(null=True, unique=True, verbose_name='Custom id'),
        ),
        migrations.AddField(
            model_name='book',
            name='ean',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
    ]
