# Generated by Django 3.0.5 on 2022-01-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0069_auto_20220126_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='barcode',
            new_name='id_barcode',
        ),
        migrations.AlterField(
            model_name='moviecase',
            name='ean',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
    ]
