# Generated by Django 3.0.5 on 2022-01-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0070_auto_20220127_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='ean',
        ),
        migrations.RemoveField(
            model_name='moviecase',
            name='ean',
        ),
        migrations.AddField(
            model_name='element',
            name='ean',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
    ]
