# Generated by Django 3.0.5 on 2022-01-27 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0071_auto_20220127_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='ean',
        ),
    ]
