# Generated by Django 3.0.5 on 2022-01-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0072_remove_element_ean'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='ean',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
    ]
