# Generated by Django 3.0.5 on 2022-02-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0076_staffsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='staffsettings',
            name='open_day_borrow',
            field=models.ManyToManyField(to='Mindkeepr.Days'),
        ),
    ]
