# Generated by Django 3.0.5 on 2022-02-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0079_auto_20220205_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='staffsettings',
            name='sales_department',
        ),
        migrations.RemoveField(
            model_name='staffsettings',
            name='twilio_account_sid',
        ),
        migrations.RemoveField(
            model_name='staffsettings',
            name='twilio_auth_token',
        ),
        migrations.RemoveField(
            model_name='staffsettings',
            name='twilio_phone_number',
        ),
        migrations.AlterField(
            model_name='moveevent',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'Reserved'), ('FREE', 'Free')], max_length=200, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='stockrepartition',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'Reserved'), ('FREE', 'Free')], max_length=200, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='staffsettings',
            name='exceptionnaly_close_day_borrow',
            field=models.ManyToManyField(related_name='close_days', to='Mindkeepr.DayException'),
        ),
        migrations.AddField(
            model_name='staffsettings',
            name='exceptionnaly_open_day_borrow',
            field=models.ManyToManyField(related_name='open_days', to='Mindkeepr.DayException'),
        ),
    ]
