# Generated by Django 3.0.5 on 2022-02-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0080_auto_20220206_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='barcode_effective',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='moveevent',
            name='status',
            field=models.CharField(choices=[('FREE', 'Free'), ('RESERVED', 'Reserved')], max_length=200, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='staffsettings',
            name='exceptionnaly_close_day_borrow',
            field=models.ManyToManyField(blank=True, null=True, related_name='close_days', to='Mindkeepr.DayException'),
        ),
        migrations.AlterField(
            model_name='staffsettings',
            name='exceptionnaly_open_day_borrow',
            field=models.ManyToManyField(blank=True, null=True, related_name='open_days', to='Mindkeepr.DayException'),
        ),
        migrations.AlterField(
            model_name='stockrepartition',
            name='status',
            field=models.CharField(choices=[('FREE', 'Free'), ('RESERVED', 'Reserved')], max_length=200, verbose_name='Status'),
        ),
    ]
