# Generated by Django 3.0.5 on 2022-02-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0081_auto_20220212_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='custom_id_generic',
            field=models.IntegerField(blank=True, null=True, verbose_name='Custom generic'),
        ),
        migrations.AlterField(
            model_name='element',
            name='barcode_effective',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
    ]
