# Generated by Django 3.0.5 on 2022-02-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0082_auto_20220213_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='custom_id_prefix_generic',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
