# Generated by Django 3.0.5 on 2022-02-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0083_element_custom_id_prefix_generic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={},
        ),
        migrations.RemoveField(
            model_name='book',
            name='custom_id',
        ),
        migrations.RemoveField(
            model_name='element',
            name='ean',
        ),
        migrations.RemoveField(
            model_name='moviecase',
            name='custom_id',
        ),
        migrations.AddField(
            model_name='moviecase',
            name='ean',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='element',
            constraint=models.UniqueConstraint(fields=('custom_id_generic', 'custom_id_prefix_generic'), name='Unicity of custom id by prefix'),
        ),
    ]
