# Generated by Django 3.0.5 on 2022-02-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0086_auto_20220213_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviecase',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterField(
            model_name='element',
            name='custom_id_generic',
            field=models.IntegerField(blank=True, null=True, verbose_name='Custom id'),
        ),
    ]
