# Generated by Django 3.0.5 on 2022-02-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0087_auto_20220213_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviecase',
            options={},
        ),
        migrations.RemoveField(
            model_name='element',
            name='default_location',
        ),
        migrations.AddField(
            model_name='moviecase',
            name='custom_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Custom id'),
        ),
    ]
