# Generated by Django 3.0.5 on 2022-02-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0088_auto_20220213_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moveevent',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'Reserved'), ('FREE', 'Free')], max_length=200, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='stockrepartition',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'Reserved'), ('FREE', 'Free')], max_length=200, verbose_name='Status'),
        ),
        migrations.AddConstraint(
            model_name='moviecase',
            constraint=models.UniqueConstraint(fields=('custom_id', 'format_disk'), name='Unicity  of custom id by format (DVD/Bluray)'),
        ),
    ]
