# Generated by Django 3.0.5 on 2022-02-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0089_auto_20220213_1655'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='moviecase',
            constraint=models.UniqueConstraint(fields=('custom_id', 'format_disk'), name='Unicity of custom id by format (DVD/Bluray)'),
        ),
        migrations.RemoveConstraint(
            model_name='moviecase',
            name='Unicity  of custom id by format (DVD/Bluray)',
        ),
        migrations.AlterField(
            model_name='moveevent',
            name='status',
            field=models.CharField(choices=[('FREE', 'Free'), ('RESERVED', 'Reserved')], max_length=200, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='stockrepartition',
            name='status',
            field=models.CharField(choices=[('FREE', 'Free'), ('RESERVED', 'Reserved')], max_length=200, verbose_name='Status'),
        ),
    ]
