# Generated by Django 3.0.5 on 2022-02-13 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0091_auto_20220213_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviecase',
            options={'base_manager_name': 'objects'},
        ),
    ]
