# Generated by Django 3.0.5 on 2022-02-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0093_auto_20220213_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='use_ean_as_effective_barcode',
            field=models.BooleanField(default=True, verbose_name='Use ean as effective barcode'),
        ),
        migrations.AlterField(
            model_name='moviecase',
            name='category_box',
            field=models.CharField(choices=[('CHI', 'Children'), ('HOR', 'Horror'), ('COM', 'Comedy'), ('DRA', 'Drama'), ('ACT', 'Action')], default='UNK', max_length=3),
        ),
        migrations.AlterField(
            model_name='moviecase',
            name='use_ean_as_effective_barcode',
            field=models.BooleanField(default=True, verbose_name='Use ean as effective barcode'),
        ),
    ]
