# Generated by Django 3.0.5 on 2022-02-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0094_auto_20220213_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecase',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Is new'),
        ),
    ]
