# Generated by Django 3.0.5 on 2022-02-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0097_element_custom_id_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ean',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='moviecase',
            name='ean',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
