# Generated by Django 3.0.5 on 2022-02-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0101_auto_20220220_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookabstract',
            name='open_library_api_id',
        ),
        migrations.AlterField(
            model_name='bookabstract',
            name='summary',
            field=models.CharField(blank=True, max_length=2300, null=True),
        ),
    ]
