# Generated by Django 3.0.5 on 2022-02-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0102_auto_20220223_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='format_book',
            field=models.CharField(choices=[('NOV', 'Novel'), ('COM', 'Comic Book')], default='NOV', max_length=3),
        ),
        migrations.AlterField(
            model_name='moveevent',
            name='status',
            field=models.CharField(choices=[('FREE', 'Free'), ('RESERVED', 'Reserved')], max_length=200, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='stockrepartition',
            name='status',
            field=models.CharField(choices=[('FREE', 'Free'), ('RESERVED', 'Reserved')], max_length=200, verbose_name='Status'),
        ),
    ]
