# Generated by Django 3.0.5 on 2022-03-09 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0103_auto_20220224_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGame',
            fields=[
                ('element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Mindkeepr.Element')),
                ('ean', models.CharField(max_length=13, null=True)),
                ('use_ean_as_effective_barcode', models.BooleanField(default=True, verbose_name='Use ean as effective barcode')),
                ('nb_disk', models.IntegerField(default=1, verbose_name='Number of disks')),
                ('platform', models.CharField(choices=[('WIU', 'Wii U'), ('PS4', 'Playstation 4'), ('SWI', 'Switch')], default='SWI', max_length=3)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('Mindkeepr.element',),
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.AlterField(
            model_name='staffsettings',
            name='exceptionnaly_close_day_borrow',
            field=models.ManyToManyField(blank=True, related_name='close_days', to='Mindkeepr.DayException'),
        ),
        migrations.AlterField(
            model_name='staffsettings',
            name='exceptionnaly_open_day_borrow',
            field=models.ManyToManyField(blank=True, related_name='open_days', to='Mindkeepr.DayException'),
        ),
    ]
