# Generated by Django 3.0.5 on 2022-03-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0104_auto_20220309_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(choices=[('HHW', 'Hardware'), ('GHW', 'Gaming Hardware'), ('VHW', 'Video Hardware')], default='HHW', max_length=3),
        ),
        migrations.AlterField(
            model_name='moveevent',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'Reserved'), ('FREE', 'Free')], max_length=200, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='stockrepartition',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'Reserved'), ('FREE', 'Free')], max_length=200, verbose_name='Status'),
        ),
    ]
