# Generated by Django 3.0.5 on 2022-03-26 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('Mindkeepr', '0106_auto_20220323_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieProductGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=30)),
                ('name_fr', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='element_images')),
                ('short_description', models.CharField(max_length=150, verbose_name='description')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_mindkeepr.product_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_abstract',
        ),
        migrations.CreateModel(
            name='ProductBook',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Mindkeepr.Product')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('summary', models.CharField(blank=True, max_length=2300, null=True)),
                ('nb_pages', models.IntegerField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='book_images/cover')),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('author_2', models.CharField(blank=True, max_length=100, null=True)),
                ('publisher', models.CharField(blank=True, max_length=100, null=True)),
                ('ean', models.CharField(max_length=13, null=True)),
                ('book_type', models.CharField(choices=[('CMB', 'Comic Book'), ('NOV', 'Novel')], default='CMB', max_length=3)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('Mindkeepr.product',),
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
        migrations.AddField(
            model_name='element',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mindkeepr.Product'),
        ),
    ]
