# Generated by Django 3.0.5 on 2022-03-26 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0107_auto_20220326_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Mindkeepr.Product')),
                ('original_language', models.CharField(blank=True, max_length=30, null=True)),
                ('original_title', models.CharField(blank=True, max_length=100, null=True)),
                ('nationality', models.CharField(blank=True, max_length=30, null=True)),
                ('local_title', models.CharField(max_length=100)),
                ('catch_phrase', models.CharField(blank=True, max_length=300, null=True)),
                ('synopsis', models.CharField(blank=True, max_length=1000, null=True)),
                ('time_length', models.IntegerField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('backdrop_image', models.ImageField(blank=True, null=True, upload_to='movie_product_images/backdrop')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movie_product_images/poster')),
                ('budget', models.FloatField(null=True)),
                ('remote_api_id', models.IntegerField(blank=True)),
                ('trailer_video_url', models.URLField(blank=True, null=True)),
                ('genres', models.ManyToManyField(to='Mindkeepr.MovieProductGenre')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('Mindkeepr.product',),
        ),
        migrations.DeleteModel(
            name='BookAbstract',
        ),
        migrations.RemoveField(
            model_name='moviecase',
            name='movie',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='MovieGenre',
        ),
    ]
