# Generated by Django 3.0.5 on 2022-03-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('Mindkeepr', '0108_auto_20220326_2009'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductBook',
            new_name='BookProduct',
        ),
        migrations.AlterField(
            model_name='moveevent',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'Reserved'), ('FREE', 'Free')], max_length=200, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='stockrepartition',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'Reserved'), ('FREE', 'Free')], max_length=200, verbose_name='Status'),
        ),
    ]
