# Generated by Django 3.0.5 on 2022-03-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0109_auto_20220326_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookproduct',
            name='title',
        ),
        migrations.RemoveField(
            model_name='movieproduct',
            name='local_title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='Benoit', max_length=150, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moveevent',
            name='status',
            field=models.CharField(choices=[('FREE', 'Free'), ('RESERVED', 'Reserved')], max_length=200, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='stockrepartition',
            name='status',
            field=models.CharField(choices=[('FREE', 'Free'), ('RESERVED', 'Reserved')], max_length=200, verbose_name='Status'),
        ),
    ]
