# Generated by Django 3.0.5 on 2022-04-03 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0110_auto_20220326_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGameProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Mindkeepr.Product')),
                ('platform', models.CharField(choices=[('WII', 'Wii'), ('WIU', 'Wii U'), ('PS4', 'Playstation 4'), ('SWI', 'Switch')], default='SWI', max_length=3)),
                ('nb_player_max', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('Mindkeepr.product',),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=150, verbose_name='description'),
        ),
    ]
