# Generated by Django 3.0.5 on 2022-04-03 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0111_auto_20220403_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Mindkeepr.Product')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('Mindkeepr.product',),
        ),
        migrations.AlterField(
            model_name='movieproduct',
            name='budget',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
