# Generated by Django 3.1.14 on 2023-02-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0117_auto_20230129_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moveevent',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'Reserved'), ('FREE', 'Free')], max_length=200, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='stockrepartition',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'Reserved'), ('FREE', 'Free')], max_length=200, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='platform',
            field=models.CharField(choices=[('WIU', 'Wii U'), ('PS4', 'Playstation 4'), ('PS5', 'Playstation 5'), ('XBO', 'Xbox One'), ('SWI', 'Switch')], default='SWI', max_length=3),
        ),
        migrations.AlterField(
            model_name='videogameproduct',
            name='platform',
            field=models.CharField(choices=[('WII', 'Wii'), ('WIU', 'Wii U'), ('PS4', 'Playstation 4'), ('PS4', 'Playstation 5'), ('XBO', 'Xbox One'), ('SWI', 'Switch')], default='SWI', max_length=3),
        ),
    ]
