# Generated by Django 3.1.14 on 2023-02-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mindkeepr', '0118_auto_20230219_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogameproduct',
            name='platform',
            field=models.CharField(choices=[('WII', 'Wii'), ('WIU', 'Wii U'), ('PS4', 'Playstation 4'), ('PS5', 'Playstation 5'), ('XBO', 'Xbox One'), ('SWI', 'Switch')], default='SWI', max_length=3),
        ),
    ]
